version: '3.9'
services:
    telestrainer:
        build:
            context: ''
            dockerfile: docker/Dockerfile
        container_name: telestrainer
        networks:
            - vpc

networks:
  vpc:
    name: telestrainer-network